spring.application.name=student-management
# spring.datasource.url=jdbc:postgresql://localhost:5432/student_db_for_new
# spring.datasource.username=postgres
# spring.datasource.password=Root@123


# this is for local testing docker build
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/student_db_for_new
spring.datasource.username=postgres
spring.datasource.password=Root@123
server.port=8080





# this is for deployment in render
# server.port=${PORT:8080}
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

